name: 'Get PR'
description: 'This action get pull request associated with the commit.'
inputs:
  repo-token:  # id of input
    description: 'The repository token, i.e. secrets.GITHUB_TOKEN'
    required: true
outputs:
  pull_request: # id of output
    description: 'The pull request associated with the commit'
runs:
  using: 'node12'
  main: 'dist/index.js'
