on:
  - push

jobs:
  get_pr_job:
    runs-on: ubuntu-latest
    name: A job to get pull request
    steps:
    - name: Get PR action step
      id: pr_step
      uses: shioyang/get-pr-action@v2.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: See found PR
      run: echo "${{ steps.pr_step.outputs.pull_request }}"
