on:
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: shioyang/get-pr-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
